version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dante
      POSTGRES_PASSWORD: dante123456
      POSTGRES_DB: notebook_DB
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python3 manage.py migrate
      && python3 manage.py start_users_set
      && python3 manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db