# Generated by Django 3.2.12 on 2022-02-23 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preson',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Имя', max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия', max_length=64, verbose_name='Фамилия')),
                ('parent_name', models.CharField(blank=True, help_text='Отчество', max_length=64, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, help_text='дата рождения', verbose_name='Дата рождения')),
                ('email', models.EmailField(help_text='E-mail', max_length=254, unique=True, verbose_name='E-mail')),
                ('was_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Активен')),
            ],
        ),
    ]
