# Generated by Django 3.2.10 on 2022-03-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Логин пользователя', max_length=64, unique=True, verbose_name='Логин'),
        ),
    ]
