# Generated by Django 3.2.12 on 2022-04-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='Дата рождения', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя', max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Administrator'), ('M', 'Manager'), ('D', 'Developer')], help_text='Тип учетной записи', max_length=1, verbose_name='Тип учетной записи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, help_text='Фамилия', max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Логин пользователя', max_length=64, unique=True, verbose_name='Логин'),
        ),
    ]
