# Generated by Django 3.2.12 on 2022-03-02 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Наименование проекта', max_length=64, unique=True, verbose_name='Проект')),
                ('project_URL', models.CharField(blank=True, help_text='Ссылка на репозиторий', max_length=128, verbose_name='Репозиторий проекта')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Дата начала проекта', verbose_name='Дата начала проекта')),
                ('is_active', models.BooleanField(default=True, help_text='Статус проекта')),
                ('members', models.ManyToManyField(help_text='Пользователи учавствующие в проекте', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Содержание заметки', verbose_name='Текст')),
                ('short_description', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Время создания:', verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Последнее редактирование')),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.OneToOneField(help_text='Заметка создана пользователем:', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('project', models.ForeignKey(help_text='Заметка в составе проекта', on_delete=django.db.models.deletion.CASCADE, to='todo.project', verbose_name='Проект')),
            ],
        ),
    ]
