# Generated by Django 3.2.10 on 2022-03-11 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Старт проекта', verbose_name='Дата начала проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите флажок чтобы сделать проект неактивным', verbose_name='Активный статус'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='Время создания заметки', verbose_name='Время создания заметки'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='creator',
            field=models.OneToOneField(help_text='Данные пользователя создавшего заметку', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор заметки'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите флажок, чтобы сделать заметку неактивной', verbose_name='Заметка активна'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='short_description',
            field=models.CharField(help_text='Здесь можно добавить хэштэги для быстрого поиска', max_length=64, verbose_name='Краткое описание'),
        ),
    ]
