# Generated by Django 3.2.12 on 2022-04-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['is_active'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['project'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
